version: '3.9'

networks:
    nginx-php-mysql:

services:
    nginx-service:
        image: nginx:stable
        container_name: nginx-container
        ports:
            - "10100:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql57-service

        networks:
            - nginx-php-mysql


    php82-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php82-container
        ports:
            - "10103:9000"
        volumes:
            -   ./:/var/www/app
        networks:
            - nginx-php-mysql

    mysql57-service:
        image: mysql:5.7-debian
        platform: linux/x86_64
        container_name: mysql57-container
        ports:
            - "4307:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        networks:
            nginx-php-mysql:
